"use strict";
const HEADER_SIZE = 6;

const INVALID_ID_TYPE = 7;

/** Protocol message endpoint id type define
 * Define 01 ~ 06
 * Reserved 07 ~ 0f
 */
const ENTITY_TYPE = {
    SENSOR: "n",
    APPCLIENT: "a",
    WEBCLIENT: "w",
    SERVER: "s",
    DATABASE: "d"
};

const ENDPOIONT_ID_TYPE = {
    EI_TYPE_SENSOR_TSI: 0x01,
    EI_TYPE_APP_TCI:    0x02,
    EI_TYPE_WEB_TCI:    0x03,
    EI_TYPE_SENSOR_SSN: 0x04,
    EI_TYPE_APP_USN:    0x05,
    EI_TYPE_WEB_USN:    0x06
};

const INVALID_MSG_TYPE = 0xff;

/** SSP protocol message type define
 *  Define 0x01 (1) ~ 0x08 (8)
 *  Reserved 0x09 (9) ~ 0x1e (30)
 */
const SSP_MSG_TYPE = {
    SSP_SIR_REQ: 0x01,
    SSP_SIR_RSP: 0x02,
    SSP_DCA_REQ: 0x03,
    SSP_DCA_RSP: 0x04,
    SSP_DCD_NOT: 0x05,
    SSP_DCD_ACK: 0x06,
    SSP_RAD_TRN: 0x07,
    SSP_RAD_ACK: 0x08
};
/** SAP protocol message type define
 *  Define 0x1f (31) ~ 0x44 (62)
 *  Reserved 0x3f (63) ~ 0x64 (100)
 */
const SAP_MSG_TYPE = {
    SAP_SGU_REQ: 0x1f,
    SAP_SGU_RSP: 0x20,
    SAP_UVC_REQ: 0x21,
    SAP_UVC_RSP: 0x22,
    SAP_SGI_REQ: 0x23,
    SAP_SGI_RSP: 0x24,
    SAP_SGO_NOT: 0x25,
    SAP_SGO_ACK: 0x26,
    SAP_UPC_REQ: 0x27,
    SAP_UPC_RSP: 0x28,
    SAP_FPU_REQ: 0x29,
    SAP_FPU_RSP: 0x2a,
    SAP_SRG_REQ: 0x2b,
    SAP_SRG_RSP: 0x2c,
    SAP_SAS_REQ: 0x2d,
    SAP_SAS_RSP: 0x2e,
    SAP_SDD_REQ: 0x2f,
    SAP_SDD_RSP: 0x30,
    SAP_SLV_REQ: 0x31,
    SAP_SLV_RSP: 0x32,
    SAP_DCA_REQ: 0x33,
    SAP_DCA_RSP: 0x34,
    SAP_DCD_NOT: 0x35,
    SAP_DCD_ACK: 0x36,
    SAP_RHD_TRN: 0x37,
    SAP_RHD_ACK: 0x38,
    SAP_RAV_REQ: 0x39,
    SAP_RAV_RSP: 0x40,
    SAP_HHV_REQ: 0x41,
    SAP_HHV_RSP: 0x42,
    SAP_KAS_REQ: 0x43,
    SAP_KAS_RSP: 0x44
};
/** SWP protocol message type define
 *  Define 0x65 (101) ~ 0x8e (142)
 *  Reserved 0x8f (143) ~ 0xaa (170)
 */
const SWP_MSG_TYPE = {
    SWP_SGU_REQ: 0x65,
    SWP_SGU_RSP: 0x66,
    SWP_UVC_REQ: 0x67,
    SWP_UVC_RSP: 0x68,
    SWP_SGI_REQ: 0x69,
    SWP_SGI_RSP: 0x6a,
    SWP_SGO_NOT: 0x6b,
    SWP_SGO_ACK: 0x6c,
    SWP_UPC_REQ: 0x6d,
    SWP_UPC_RSP: 0x6e,
    SWP_FPU_REQ: 0x6f,
    SWP_FPU_RSP: 0x70,
    SWP_UDR_REQ: 0x71,
    SWP_UDR_RSP: 0x72,
    SWP_AUV_REQ: 0x73,
    SWP_AUV_RSP: 0x74,
    SWP_ASR_REQ: 0x75,
    SWP_ASR_RSP: 0x76,
    SWP_ASD_REQ: 0x77,
    SWP_ASD_RSP: 0x78,
    SWP_ASV_REQ: 0x79,
    SWP_ASV_RSP: 0x7a,
    SWP_SRG_REQ: 0x7b,
    SWP_SRG_RSP: 0x7c,
    SWP_SAS_REQ: 0x7d,
    SWP_SAS_RSP: 0x7e,
    SWP_SDD_REQ: 0x7f,
    SWP_SDD_RSP: 0x80,
    SWP_SLV_REQ: 0x81,
    SWP_SLV_RSP: 0x82,
    SWP_RAV_REQ: 0x83,
    SWP_RAV_RSP: 0x84,
    SWP_RHV_REQ: 0x85,
    SWP_RHV_RSP: 0x86,
    SWP_HAV_REQ: 0x87,
    SWP_HAV_RSP: 0x88,
    SWP_SHR_REQ: 0x89,
    SWP_SHR_RSP: 0x8a,
    SWP_HHV_REQ: 0x8b,
    SWP_HHV_RSP: 0x8c,
    SWP_KAS_REQ: 0x8d,
    SWP_KAS_RSP: 0x8e
};

/** SDP protocol message type define
 *  Define 0xab (171) ~ 0xd8 (216)
 *  Reserved 0xd9 (217) ~ 0xfe (254)
 */
const SDP_MSG_TYPE = {
    SDP_SGU_REQ: 0xab,
    SDP_SGU_RSP: 0xac,
    SDP_UVC_REQ: 0xad,
    SDP_UVC_RSP: 0xae,
    SDP_SGI_REQ: 0xaf,
    SDP_SGI_RSP: 0xb0,
    SDP_SGO_NOT: 0xb1,
    SDP_SGO_ACK: 0xb2,
    SDP_UPC_REQ: 0xb3,
    SDP_UPC_RSP: 0xb4,
    SDP_FPU_REQ: 0xb5,
    SDP_FPU_RSP: 0xb6,
    SDP_UDR_REQ: 0xb7,
    SDP_UDR_RSP: 0xb8,
    SDP_AUV_REQ: 0xb9,
    SDP_AUV_RSP: 0xba,
    SDP_ASR_REQ: 0xbb,
    SDP_ASR_RSP: 0xbc,
    SDP_ASD_REQ: 0xbd,
    SDP_ASD_RSP: 0xbe,
    SDP_ASV_REQ: 0xbf,
    SDP_ASV_RSP: 0xc0,
    SDP_SRG_REQ: 0xc1,
    SDP_SRG_RSP: 0xc2,
    SDP_SAS_REQ: 0xc3,
    SDP_SAS_RSP: 0xc4,
    SDP_SDD_REQ: 0xc5,
    SDP_SDD_RSP: 0xc6,
    SDP_SLV_REQ: 0xc7,
    SDP_SLV_RSP: 0xc8,
    SDP_SIR_REQ: 0xc9,
    SDP_SIR_RSP: 0xca,
    SDP_DCA_REQ: 0xcb,
    SDP_DCA_RSP: 0xcc,
    SDP_DCD_NOT: 0xcd,
    SDP_DCD_ACK: 0xce,
    SDP_RAD_TRN: 0xcf,
    SDP_RAD_ACK: 0xd0,
    SDP_RHD_TRN: 0xd1,
    SDP_RHD_ACK: 0xd2,
    SDP_HAV_REQ: 0xd3,
    SDP_HAV_RSP: 0xd4,
    SDP_SHR_REQ: 0xd5,
    SDP_SHR_RSP: 0xd6,
    SDP_HHV_REQ: 0xd7,
    SDP_HHV_RSP: 0xd8
};
const SSP_MSG_RESCODE = {
    RESCODE_SSP_SIR: {
        RESCODE_SSP_SIR_OK: 0,
        RESCODE_SSP_SIR_OTHER: 1,
        RESCODE_SSP_SIR_CONFLICT_OF_TEMPORARY_SENSOR_ID: 2,
        RESCODE_SSP_SIR_NOT_EXIST_WIFI_MAC_ADDRESS: 3,
        RESCODE_SSP_SIR_NOT_AN_ASSOCIATED_SENSOR_WITH_ANY_USER: 4
    },
    RESCODE_SSP_DCA: {
        RESCODE_SSP_DCA_OK: 0,
        RESCODE_SSP_DCA_OTHER: 1,
        RESCODE_SSP_DCA_NOT_EXIST_SENSOR_SERIAL_NUMBER: 2,
        RESCODE_SSP_DCA_MISMACH_INITIAL_GPS_INFORMATION: 3,
        RESCODE_SSP_DCA_NOT_AN_ASSOCIATED_SENSOR_WITH_ANY_USER: 4
    },
    RESCODE_SSP_DCD: {
        RESCODE_SSP_DCD_OK: 0,
        RESCODE_SSP_DCD_OTHER: 1,
        RESCODE_SSP_DCD_UNALLOCATED_CONNECTION_ID: 2
    }

};
const SAP_MSG_RESCODE = {
    RESCODE_SAP_SGU: {
        RESCODE_SAP_SGU_OK: 0,
        RESCODE_SAP_SGU_OTHER: 1,
        RESCODE_SAP_SGU_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SAP_SGU_DUPLICATE_OF_USER_ID: 3
    },
    RESCODE_SAP_UVC: {
        RESCODE_SAP_UVC_OK: 0,
        RESCODE_SAP_UVC_OTHER: 1,
        RESCODE_SAP_UVC_DUPLICATE_OF_USER_ID: 2,
        RESCODE_SAP_UVC_NOT_EXIST_TEMPORARY_CLIENT_ID: 3,
        RESCODE_SAP_UVC_INCORRECT_AC_UNDER_THE_VC: 4
    },
    RESCODE_SAP_SGI: {
        RESCODE_SAP_SGI_OK: 0,
        RESCODE_SAP_SGI_OTHER: 1,
        RESCODE_SAP_SGI_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SAP_SGI_NOT_EXIST_USER_ID: 3,
        RESCODE_SAP_SGI_INCORRECT_CURRENT_USER_PASSWORD: 4
    },
    RESCODE_SAP_SGO: {
        RESCODE_SAP_SGO_OK: 0,
        RESCODE_SAP_SGO_OTHER: 1,
        RESCODE_SAP_SGO_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_SGO_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SAP_UPC: {
        RESCODE_SAP_UPC_OK: 0,
        RESCODE_SAP_UPC_OTHER: 1,
        RESCODE_SAP_UPC_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_UPC_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SAP_UPC_INCORRECT_CURRENT_USER_PASSWORD: 4
    },
    RESCODE_SAP_FPU: {
        RESCODE_SAP_FPU_OK: 0,
        RESCODE_SAP_FPU_OTHER: 1,
        RESCODE_SAP_FPU_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SAP_FPU_INCORRECT_USER_INFORMATION: 3,
        RESCODE_SAP_FPU_NOT_EXIST_USER_ID: 4
    },
    RESCODE_SAP_SRG: {
        RESCODE_SAP_SRG_OK: 0,
        RESCODE_SAP_SRG_OTHER: 1,
        RESCODE_SAP_SRG_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_SRG_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SAP_SAS: {
        RESCODE_SAP_SAS_OK: 0,
        RESCODE_SAP_SAS_OTHER: 1,
        RESCODE_SAP_SAS_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_SAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SAP_SAS_NOT_EXIST_WIFI_MAC_ADDRESS: 4,
        RESCODE_SAP_SAS_THE_REQUESTED_WIFI_MAC_ADDRESS_WAS_ALREADY_ASSOCIATED_OWN_USN: 5,
        RESCODE_SAP_SAS_THE_REQUESTED_WIFI_MAC_ADDRESS_WAS_ALREADY_ASSOCIATEDOTHER_USN: 6
    },
    RESCODE_SAP_SDD: {
        RESCODE_SAP_SDD_OK: 0,
        RESCODE_SAP_SDD_OTHER: 1,
        RESCODE_SAP_SDD_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_SDD_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SAP_SDD_NOT_EXIST_WIFI_MAC_ADDRESS: 4,
        RESCODE_SAP_SDD_THE_REQUESTED_USN_AND_WIFI_MAC_ADDRESS_ARE_NOT_ASSOCIATED: 5
    },
    RESCODE_SAP_SLV: {
        RESCODE_SAP_SLV_OK: 0,
        RESCODE_SAP_SLV_OTHER: 1,
        RESCODE_SAP_SLV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_SLV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SAP_SLV_NOT_EXIST_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SAP_DCA: {
        RESCODE_SAP_DCA_OK: 0,
        RESCODE_SAP_DCA_OTHER: 1,
        RESCODE_SAP_DCA_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_DCA_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SAP_DCD: {
        RESCODE_SAP_DCD_OK: 0,
        RESCODE_SAP_DCD_OTHER: 1,
        RESCODE_SAP_DCD_UNALLOCATED_CONNECTION_ID: 2
    },
    RESCODE_SAP_RAV: {
        RESCODE_SAP_RAV_OK: 0,
        RESCODE_SAP_RAV_OTHER: 1,
        RESCODE_SAP_RAV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_RAV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SAP_HHV: {
        RESCODE_SAP_HHV_OK: 0,
        RESCODE_SAP_HHV_OTHER: 1,
        RESCODE_SAP_HHV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_HHV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SAP_HHV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SAP_KAS: {
        RESCODE_SAP_KAS_OK: 0,
        RESCODE_SAP_KAS_OTHER: 1,
        RESCODE_SAP_KAS_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SAP_KAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    }
};
const SWP_MSG_RESCODE = {
    RESCODE_SWP_SGU: {
        RESCODE_SWP_SGU_OK: 0,
        RESCODE_SWP_SGU_OTHER: 1,
        RESCODE_SWP_SGU_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SWP_SGU_DUPLICATE_OF_USER_ID: 3
    },
    RESCODE_SWP_UVC: {
        RESCODE_SWP_UVC_OK: 0,
        RESCODE_SWP_UVC_OTHER: 1,
        RESCODE_SWP_UVC_DUPLICATE_OF_USER_ID: 2,
        RESCODE_SWP_UVC_NOT_EXIST_TEMPORARY_CLIENT_ID: 3,
        RESCODE_SWP_UVC_INCORRECT_AC_UNDER_THE_VC: 4
    },
    RESCODE_SWP_SGI: {
        RESCODE_SWP_SGI_OK: 0,
        RESCODE_SWP_SGI_OTHER: 1,
        RESCODE_SWP_SGI_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SWP_SGI_NOT_EXIST_USER_ID: 3,
        RESCODE_SWP_SGI_INCORRECT_CURRENT_USER_PASSWORD: 4
    },
    RESCODE_SWP_SGO: {
        RESCODE_SWP_SGO_OK: 0,
        RESCODE_SWP_SGO_OTHER: 1,
        RESCODE_SWP_SGO_UNALLOCATED_USER_SEQUENCE_NUMBER: 3,
        RESCODE_SWP_SGO_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 4
    },
    RESCODE_SWP_UPC: {
        RESCODE_SWP_UPC_OK: 0,
        RESCODE_SWP_UPC_OTHER: 1,
        RESCODE_SWP_UPC_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_UPC_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_UPC_INCORRECT_CURRENT_USER_PASSWORD: 4
    },
    RESCODE_SWP_FPU: {
        RESCODE_SWP_FPU_OK: 0,
        RESCODE_SWP_FPU_OTHER: 1,
        RESCODE_SWP_FPU_CONFLICT_OF_TEMPORARY_CLIENT_ID: 2,
        RESCODE_SWP_FPU_INCORRECT_USER_INFORMATION: 3,
        RESCODE_SWP_FPU_NOT_EXIST_USER_ID: 4
    },
    RESCODE_SWP_UDR: {
        RESCODE_SWP_UDR_OK: 0,
        RESCODE_SWP_UDR_OTHER: 1,
        RESCODE_SWP_UDR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_UDR_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_UDR_INCORRECT_CURRENT_USER_PASSWORD: 4
    },
    RESCODE_SWP_AUV: {
        RESCODE_SWP_AUV_OK: 0,
        RESCODE_SWP_AUV_OTHER: 1,
        RESCODE_SWP_AUV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_AUV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_AUV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SWP_ASR: {
        RESCODE_SWP_ASR_OK: 0,
        RESCODE_SWP_ASR_OTHER: 1,
        RESCODE_SWP_ASR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_ASR_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_ASR_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SWP_ASD: {
        RESCODE_SWP_ASD_OK: 0,
        RESCODE_SWP_ASD_OTHER: 1,
        RESCODE_SWP_ASD_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_ASD_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_ASD_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4,
        RESCODE_SDP_ASD_NOT_EXIST_WIFI_MAC_ADDRESS: 5,
        RESCODE_SWP_ASD_NOT_EXIST_USER_ID: 6,
        RESCODE_SWP_ASD_THE_REQUESTED_WIFI_MAC_IS_NOT_AN_ASSOCIATED_WITH_USER_ID: 7
    },
    RESCODE_SWP_ASV: {
        RESCODE_SWP_ASV_OK: 0,
        RESCODE_SWP_ASV_OTHER: 1,
        RESCODE_SWP_ASV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_ASV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_ASV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SWP_SRG: {
        RESCODE_SWP_SRG_OK: 0,
        RESCODE_SWP_SRG_OTHER: 1,
        RESCODE_SWP_SRG_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_SRG_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SWP_SAS: {
        RESCODE_SWP_SAS_OK: 0,
        RESCODE_SWP_SAS_OTHER: 1,
        RESCODE_SWP_SAS_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_SAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SDP_SAS_NOT_EXIST_WIFI_MAC_ADDRESS: 4,
        RESCODE_SWP_SAS_THE_REQUESTED_WIFI_MAC_WAS_ALREADY_ASSOCIATED_WITH_OWN_USN: 5,
        RESCODE_SWP_SAS_THE_REQUESTED_WIFI_MAC_WAS_ALREADY_ASSOCIATED_WITH_OTHER_USN: 6
    },
    RESCODE_SWP_SDD: {
        RESCODE_SWP_SDD_OK: 0,
        RESCODE_SWP_SDD_OTHER: 1,
        RESCODE_SWP_SDD_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_SDD_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_SDD_NOT_EXIST_WIFI_MAC_ADDRESS: 4,
        RESCODE_SWP_SDD_THE_REQUESTED_USN_AND_WIFI_MAC_ADDRESS_ARE_NOT_ASSOCIATED: 5
    },
    RESCODE_SWP_SLV: {
        RESCODE_SWP_SLV_OK: 0,
        RESCODE_SWP_SLV_OTHER: 1,
        RESCODE_SWP_SLV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_SLV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SWP_RAV: {
        RESCODE_SWP_RAV_OK: 0,
        RESCODE_SWP_RAV_OTHER: 1,
        RESCODE_SWP_RAV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_RAV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SWP_RHV: {
        RESCODE_SWP_RHV_OK: 0,
        RESCODE_SWP_RHV_OTHER: 1,
        RESCODE_SWP_RHV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_RHV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SWP_HAV: {
        RESCODE_SWP_HAV_OK: 0,
        RESCODE_SWP_HAV_OTHER: 1,
        RESCODE_SWP_HAV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_HAV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_HAV_REQUESTED_BY_AN_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4,
        RESCODE_SWP_HAV_NOT_EXIST_A_SENSOR_UNDER_THE_SPATIAL_TEMPORAL_SEARCH_CONDITION: 5
    },
    RESCODE_SWP_SHR: {
        RESCODE_SWP_SHR_OK: 0,
        RESCODE_SWP_SHR_OTHER: 1,
        RESCODE_SWP_SHR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_SHR_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    },
    RESCODE_SWP_HHV: {
        RESCODE_SWP_HHV_OK: 0,
        RESCODE_SWP_HHV_OTHER: 1,
        RESCODE_SWP_HHV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_HHV_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3,
        RESCODE_SWP_HHV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 4
    },
    RESCODE_SWP_KAS: {
        RESCODE_SWP_KAS_OK: 0,
        RESCODE_SWP_KAS_OTHER: 1,
        RESCODE_SWP_KAS_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SWP_KAS_INCORRECT_NUMBER_OF_SIGNED_IN_COMPLETIONS: 3
    }

};
const SDP_MSG_RESCODE = {
    RESCODE_SDP_SGU: {
        RESCODE_SDP_SGU_OK: 0,
        RESCODE_SDP_SGU_OTHER: 1,
        RESCODE_SDP_SGU_DUPLICATE_OF_USER_ID: 2
    },
    RESCODE_SDP_UVC: {
        RESCODE_SDP_UVC_OK: 0,
        RESCODE_SDP_UVC_OTHER: 1,
        RESCODE_SDP_UVC_DUPLICATE_OF_USER_ID: 2
    },
    RESCODE_SDP_SGI: {
        RESCODE_SDP_SGI_OK: 0,
        RESCODE_SDP_SGI_OTHER: 1,
        RESCODE_SDP_SGI_NOT_EXIST_USER_ID: 2,
        RESCODE_SDP_SGI_INCORRECT_CURRENT_USER_PASSWORD: 3
    },
    RESCODE_SDP_SGO: {
        RESCODE_SDP_SGO_OK: 0,
        RESCODE_SDP_SGO_OTHER: 1,
        RESCODE_SDP_SGO_UNALLOCATED_USER_SEQUENCE_NUMBER: 2
    },
    RESCODE_SDP_UPC: {
        RESCODE_SDP_UPC_OK: 0,
        RESCODE_SDP_UPC_OTHER: 1,
        RESCODE_SDP_UPC_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_UPC_INCORRECT_CURRENT_USER_PASSWORD: 3
    },
    RESCODE_SDP_FPU: {
        RESCODE_SDP_FPU_OK: 0,
        RESCODE_SDP_FPU_OTHER: 1,
        RESCODE_SDP_FPU_INCORRECT_USER_INFORMATION: 2,
        RESCODE_SDP_FPU_NOT_EXIST_USER_ID: 3
    },
    RESCODE_SDP_UDR: {
        RESCODE_SDP_UDR_OK: 0,
        RESCODE_SDP_UDR_OTHER: 1,
        RESCODE_SDP_UDR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_UDR_INCORRECT_CURRENT_USER_PASSWORD: 3
    },
    RESCODE_SDP_AUV: {
        RESCODE_SDP_AUV_OK: 0,
        RESCODE_SDP_AUV_OTHER: 1,
        RESCODE_SDP_AUV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_AUV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3
    },
    RESCODE_SDP_ASR: {
        RESCODE_SDP_ASR_OK: 0,
        RESCODE_SDP_ASR_OTHER: 1,
        RESCODE_SDP_ASR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_ASR_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3
    },
    RESCODE_SDP_ASD: {
        RESCODE_SDP_ASD_OK: 0,
        RESCODE_SDP_ASD_OTHER: 1,
        RESCODE_SDP_ASD_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_ASD_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3,
        RESCODE_SDP_ASD_NOT_EXIST_WIFI_MAC_ADDRESS: 4,
        RESCODE_SDP_ASD_NOT_EXIST_USER_ID: 5,
        RESCODE_SDP_ASD_THE_REQUESTED_WIFI_MAC_IS_NOT_AN_ASSOCIATED_WITH_USER_ID: 6
    },
    RESCODE_SDP_ASV: {
        RESCODE_SDP_ASV_OK: 0,
        RESCODE_SDP_ASV_OTHER: 1,
        RESCODE_SDP_ASV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_ASV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3
    },
    RESCODE_SDP_SRG: {
        RESCODE_SDP_SRG_OK: 0,
        RESCODE_SDP_SRG_OTHER: 1,
        RESCODE_SDP_SRG_UNALLOCATED_USER_SEQUENCE_NUMBER: 2
    },
    RESCODE_SDP_SAS: {
        RESCODE_SDP_SAS_OK: 0,
        RESCODE_SDP_SAS_OTHER: 1,
        RESCODE_SDP_SAS_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_SAS_NOT_EXIST_WIFI_MAC_ADDRESS: 3,
        RESCODE_SDP_SAS_THE_REQUESTED_WIFI_MAC_WAS_ALREADY_ASSOCIATED_WITH_OWN_USN: 4,
        RESCODE_SDP_SAS_THE_REQUESTED_WIFI_MAC_WAS_ALREADY_ASSOCIATED_WITH_OTHER_USN: 5
    },
    RESCODE_SDP_SDD: {
        RESCODE_SDP_SDD_OK: 0,
        RESCODE_SDP_SDD_OTHER: 1,
        RESCODE_SDP_SDD_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_SDD_NOT_EXIST_WIFI_MAC_ADDRESS: 3,
        RESCODE_SDP_SDD_THE_REQUESTED_USN_AND_WIFI_MAC_ADDRESS_ARE_NOT_ASSOCIATED: 4
    },
    RESCODE_SDP_SLV: {
        RESCODE_SDP_SLV_OK: 0,
        RESCODE_SDP_SLV_OTHER: 1,
        RESCODE_SDP_SLV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2
    },
    RESCODE_SDP_SIR: {
        RESCODE_SDP_SIR_OK: 0,
        RESCODE_SDP_SIR_OTHER: 1,
        RESCODE_SDP_SIR_NOT_EXIST_WIFI_MAC_ADDRESS: 2,
        RESCODE_SDP_SIR_NOT_AN_ASSOCIATED_SENSOR_WITH_ANY_USER: 3
    },
    RESCODE_SDP_DCA: {
        RESCODE_SDP_DCA_OK: 0,
        RESCODE_SDP_DCA_OTHER: 1,
        RESCODE_SDP_DCA_NOT_EXIST_USER_SEQUENCE_NUMBER_OR_SENSOR_SERIAL_NUMBER: 2,
        RESCODE_SDP_DCA_INITIAL_GPS_MISMACH: 3,
        RESCODE_SDP_DCA_NOT_AN_ASSOCIATED_SENSOR_WITH_ANY_USER: 4
    },
    RESCODE_SDP_DCD: {
        RESCODE_SDP_DCD_OK: 0,
        RESCODE_SDP_DCD_OTHER: 1,
        RESCODE_SDP_DCD_NOT_EXIST_USER_SEQUENCE_NUMBER_OR_SENSOR_SERIAL_NUMBER: 2
    },
    RESCODE_SDP_HAV: {
        RESCODE_SDP_HAV_OK: 0,
        RESCODE_SDP_HAV_OTHER: 1,
        RESCODE_SDP_HAV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_HAV_REQUESTED_BY_AN_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3,
        RESCODE_SDP_HAV_NOT_EXIST_A_SENSOR_UNDER_THE_SPATIAL_TEMPORAL_SEARCH_CONDITION: 4
    },
    RESCODE_SDP_SHR: {
        RESCODE_SDP_SHR_OK: 0,
        RESCODE_SDP_SHR_OTHER: 1,
        RESCODE_SDP_SHR_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_SHR_NOT_EXIST_A_SENSOR_UNDER_THE_SPATIAL_TEMPORAL_SEARCH_CONDITION: 3
    },
    RESCODE_SDP_HHV: {
        RESCODE_SDP_HHV_OK: 0,
        RESCODE_SDP_HHV_OTHER: 1,
        RESCODE_SDP_HHV_UNALLOCATED_USER_SEQUENCE_NUMBER: 2,
        RESCODE_SDP_HHV_UNAUTHORIZED_USER_SEQUENCE_NUMBER: 3
    }
};
const SERVER_NULL_STATE = 0;
const SERVER_TSI_STATE_ID = {
    SERVER_TSI_IDLE_STATE:                          0x1,
    SERVER_TSI_HALF_SSN_INFORMED_STATE:             0x2,
    SERVER_TSI_SSN_INFORMED_STATE:                  0x3
}

const SERVER_SSN_STATE_ID = {
    SERVER_SSN_IDLE_STATE:                          0x1,
    SERVER_SSN_SSN_INFORMED_STATE:                  0x2,
    SERVER_SSN_HALF_CID_INFORMED_STATE:             0x3,
    SERVER_SSN_CID_INFORMED_STATE:                  0x4,
    SERVER_SSN_HALF_IDLE_STATE:                     0x5
}

const SERVER_TCI_STATE_ID = {
    SERVER_TCI_IDLE_STATE:                          0x1,
    SERVER_TCI_USER_ID_DUPLICATE_REQUESTED_STATE:   0x2,
    SERVER_TCI_USER_ID_AVAILABLITY_CONFIRMED_STATE: 0x3,
    SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE:       0x4,
    SERVER_TCI_USN_ALLOCATED_STATE:                 0x5,
    SERVER_TCI_HALF_USN_INFORMED_STATE:             0x6,
    SERVER_TCI_HALF_IDLE_STATE:                     0x7
}

const SERVER_USN_STATE_ID = {
    SERVER_USN_IDLE_STATE:                          0x1,
    SERVER_USN_USN_INFORMED_STATE:                  0x2,
    SERVER_USN_HALF_CID_INFORMED_STATE:             0x3,
    SERVER_USN_CID_INFORMED_STATE:                  0x4,
    SERVER_USN_HALF_CID_RELEASED_STATE:             0x5,
    SERVER_USN_HALF_IDLE_STATE:                     0x6
}

const DATABASE_USN_SSN_STATE_ID = {
    DATABASE_USN_SSN_IDLE_STATE:                    0x1,
    DATABASE_USN_SSN_SSN_ALLOCATED_STATE:           0x2,
    DATABASE_SSN_SSN_ASSOCIATED_STATE:              0x3,
    DATABASE_USN_SSN_HALF_IDLE_STATE:               0x4
}
const DATABASE_SSN_STATE_ID = {
    DATABASE_SSN_IDLE_STATE:                        0x1,
    DATABASE_SSN_INFORMED_STATE:                    0x2,
    DATABASE_SSN_CID_ALLOACATED_STATE:              0x3,
    DATABASE_SSN_HALF_IDLE_STATE:                   0x4
}
const DATABASE_TCI_STATE_ID = {
    DATABASE_TCI_IDLE_STATE:                        0x1,
    DATABASE_TCI_UNIQUE_USER_ID_CONFIRMED_STATE:    0x2,
    DATABASE_USN_ALLOCATED_STATE:                   0x3
}

const DATABASE_USN_STATE_ID = {
    DATABASE_USN_IDLE_STATE:                        0x1,
    DATABASE_USN_USN_INFORMED_STATE:                0x2,
    DATABASE_USN_CID_INFORMED_STATE:                0x3,
    DATABASE_USN_CID_RELEASED_STATE:                0x4,
    DATABASE_USN_HALF_IDlE_STATE:                   0x5
}
/**
 * Receivable message by state in server
 * Server
 *  - TSI
 *  - SSN
 *  - TCI
 *  - USN
 */

const SERVER_RECV_STATE_BY_MSG = {
    SSP_SIR_REQ: [
        SERVER_TSI_STATE_ID.SERVER_TSI_IDLE_STATE,
        SERVER_TSI_STATE_ID.SERVER_TSI_HALF_SSN_INFORMED_STATE,
        SERVER_TSI_STATE_ID.SERVER_TSI_SSN_INFORMED_STATE
    ],
    SSP_DCA_REQ: [
        SERVER_SSN_STATE_ID.SERVER_SSN_IDLE_STATE,
        SERVER_SSN_STATE_ID.SERVER_SSN_HALF_CID_INFORMED_STATE,
        SERVER_SSN_STATE_ID.SERVER_SSN_CID_INFORMED_STATE
    ],
    SSP_DCD_NOT: [
        SERVER_SSN_STATE_ID.SERVER_SSN_CID_INFORMED_STATE,
        SERVER_SSN_STATE_ID.SERVER_SSN_HALF_IDLE_STATE
    ],
    SSP_RAD_TRN: [
        SERVER_SSN_STATE_ID.SERVER_SSN_CID_INFORMED_STATE
    ],
    SAP_SGU_REQ: [
        SERVER_TCI_STATE_ID.SERVER_TCI_IDLE_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_DUPLICATE_REQUESTED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_AVAILABLITY_CONFIRMED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USN_ALLOCATED_STATE
    ],
    SAP_UVC_REQ: [
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_AVAILABLITY_CONFIRMED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USN_ALLOCATED_STATE
    ],
    SAP_SGI_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SAP_SGO_NOT: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_CID_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_CID_RELEASED_STATE
    ],
    SAP_UPC_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_FPU_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SAP_SRG_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_SAS_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_SDD_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_SLV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_DCA_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_CID_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_DCD_NOT: [
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_RHD_TRN: [
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_RAV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_HHV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SAP_KAS_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SWP_SGU_REQ: [
        SERVER_TCI_STATE_ID.SERVER_TCI_IDLE_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_DUPLICATE_REQUESTED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_AVAILABLITY_CONFIRMED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USN_ALLOCATED_STATE
    ],
    SWP_UVC_REQ: [
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_AVAILABLITY_CONFIRMED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE,
        SERVER_TCI_STATE_ID.SERVER_TCI_USN_ALLOCATED_STATE
    ],
    SWP_SGI_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SGO_NOT: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_UPC_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_FPU_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SWP_UDR_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SWP_AUV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_ASR_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_ASD_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_ASV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SRG_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SAS_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SDD_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SLV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_RAV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_RHV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_HAV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_SHR_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_HHV_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SWP_KAS_REQ: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE
    ],
    SDP_SGU_RSP: [
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_ID_DUPLICATE_REQUESTED_STATE
    ],
    SDP_UVC_RSP: [
        SERVER_TCI_STATE_ID.SERVER_TCI_USER_HALF_USN_ALLOCATED_STATE
    ],
    SDP_SGI_RSP: [
        SERVER_TCI_STATE_ID.SERVER_TCI_HALF_USN_INFORMED_STATE
    ],
    SDP_SGO_ACK: [
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SDP_UPC_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_FPU_RSP: [
        SERVER_TCI_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SDP_UDR_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SDP_AUV_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_ASR_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_ASD_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_ASV_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SRG_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SAS_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SDD_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SLV_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SIR_RSP: [
        SERVER_TSI_STATE_ID.SERVER_TSI_HALF_SSN_INFORMED_STATE
    ],
    SDP_DCA_RSP: [
        SERVER_SSN_STATE_ID.SERVER_SSN_HALF_CID_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_CID_INFORMED_STATE
    ],
    SDP_DCD_ACK: [
        SERVER_SSN_STATE_ID.SERVER_SSN_HALF_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_HALF_IDLE_STATE
    ],
    SDP_RAD_ACK: [
        SERVER_SSN_STATE_ID.SERVER_SSN_CID_INFORMED_STATE
    ],
    SDP_RHD_ACK: [
        SERVER_SSN_STATE_ID.SERVER_SSN_CID_INFORMED_STATE
    ],
    SDP_HAV_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_SHR_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_IDLE_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ],
    SDP_HHV_RSP: [
        SERVER_USN_STATE_ID.SERVER_USN_USN_INFORMED_STATE,
        SERVER_USN_STATE_ID.SERVER_USN_CID_INFORMED_STATE
    ]

};
const DATABASE_RECV_STATE_BY_MSG = {
    SDP_SGU_REQ: [
        DATABASE_TCI_STATE_ID.DATABASE_TCI_IDLE_STATE,
        DATABASE_TCI_STATE_ID.DATABASE_TCI_UNIQUE_USER_ID_CONFIRMED_STATE
    ],
    SDP_UVC_REQ: [
        DATABASE_TCI_STATE_ID.DATABASE_TCI_UNIQUE_USER_ID_CONFIRMED_STATE,
        DATABASE_TCI_STATE_ID.DATABASE_USN_ALLOCATED_STATE
    ],
    SDP_SGI_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_IDLE_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_RELEASED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_HALF_IDlE_STATE
    ],
    SDP_SGO_NOT: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_RELEASED_STATE,
        DATABASE_USN_STATE_ID.HALF_IDLE_STATE
    ],
    SDP_UPC_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE
    ],
    SDP_FPU_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_IDLE_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_RELEASED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_HALF_IDlE_STATE
    ],
    SDP_UDR_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_AUV_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_ASR_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_ASD_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_ASV_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_SRG_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_IDLE_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ALLOCATED_STATE
    ],
    SDP_SAS_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ASSOCIATED_STATE
    ],
    SDP_SDD_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ALLOCATED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ASSOCIATED_STATE
    ],
    SDP_SLV_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
    ],
    SDP_SIR_REQ: [
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ALLOCATED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABASE_USN_SSN_SSN_ASSOCIATED_STATE
    ],
    SDP_DCA_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE,
        DATABASE_USN_SSN_STATE_ID.DATABSE_USN_SSN_INFORMED_STATE
    ],
    SDP_DCD_NOT: [
        DATABASE_SSN_STATE_ID.DATABASE_SSN_CID_ALLOACATED_STATE,
        DATABASE_SSN_STATE_ID.DATABASE_SSN_HALF_IDLE_STATE
    ],
    SDP_RAD_TRN: [
        DATABASE_SSN_STATE_ID.DATABASE_SSN_CID_ALLOACATED_STATE
    ],
    SDP_RHD_TRN: [
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE
    ],
    SDP_HAV_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_SHR_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_IDLE_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE
    ],
    SDP_HHV_REQ: [
        DATABASE_USN_STATE_ID.DATABASE_USN_USN_INFORMED_STATE,
        DATABASE_USN_STATE_ID.DATABASE_USN_CID_INFORMED_STATE
    ]
};

/**
 * Receivable message by state in database
 * Database
 *  - TSI
 *  - SSN
 *  - TCI
 *  - USN
 */

/**
 * Server timer define
 */
const SERVER_TIMER = {
    T701: 5,
    T702: 5,
    T703: 5,
    T704: 5,
    T705: 5,
    T706: 5,
    T707: 5,
    T708: 5,
    T709: 5,
    T710: 5,
    T711: 5,
    T712: 5,
    T713: 5,
    T714: 5,
    T715: 5,
    T716: 5,
    T717: 5,
    T718: 5,
    T719: 5,
    T720: 5,
    T721: 5,
    T722: 5,
    T723: 5,
    T801: 180,
    T802: 5,
    T803: 5,
    T804: 5,
    T805: 1,    //mti
    T806: 30,   //tti
    T831: 5,
    T832: 300,
    T833: 1800,
    T834: 5,
    T835: 600,
    T836: 5,
    T837: 1,
    T838: 30,
    T861: 5,
    T862: 300,
    T863: 1800,
};

const DATABASE_TIMER = {
    T901: 5,
    T902: 5,
    T903: 5,
    T904: 5,
    T905: 5,
    T906: 5,
    T907: 5,
    T908: 5,
    T909: 5,
    T910: 5,
    T911: 5,
    T912: 5,
    T913: 5,
    T914: 5,
    T915: 5,
    T916: 5,
    T917: 5,
    T918: 5,
    T919: 5,
    T920: 5,
    T921: 5,
    T922: 5,
    T923: 5,
    T951: 300, //TBD
    T952: 60, //TBD
    T953: 60, //TBD
    T954: 300,
    T955: 1800,
    T956: 60,
    T957: 5,
    T958: 60
};
const CLIENT_TYPE = {
    APP: 1,
    WEB: 2
}
const SIGNED_IN_STATE = {
    SIGNED_OUT: 0,
    SIGNED_IN: 1
};
const SENSOR_ACT_FLAG = {
    REGISTERED: 0,
    ASSOCATIED: 1,
    OPERATING: 2,
    DEREGISTERED: 3
}
const SENSOR_MOB_FLAG = {
    STATIONARY: 0,
    PORTABLE:                                               1
}
const USER_TYPE = {
    SUPER: 0,
    ADMIN: 1,
    USER: 2,
}
const CID_TYPE = {
    SENSOR: 0,
    APP: 1
}
module.exports = { HEADER_SIZE, 
                   ENTITY_TYPE,
                   INVALID_ID_TYPE, 
                   ENDPOIONT_ID_TYPE, 
                   INVALID_MSG_TYPE, 
                   SSP_MSG_TYPE, 
                   SAP_MSG_TYPE,
                   SWP_MSG_TYPE, 
                   SDP_MSG_TYPE,
                   SSP_MSG_RESCODE,
                   SAP_MSG_RESCODE,
                   SWP_MSG_RESCODE,
                   SDP_MSG_RESCODE,
                   SERVER_NULL_STATE,
                   SERVER_TSI_STATE_ID,
                   SERVER_SSN_STATE_ID,
                   SERVER_TCI_STATE_ID,
                   SERVER_USN_STATE_ID,
                   DATABASE_USN_SSN_STATE_ID,
                   DATABASE_SSN_STATE_ID,
                   DATABASE_TCI_STATE_ID,
                   DATABASE_USN_STATE_ID,
                   SERVER_RECV_STATE_BY_MSG,
                   DATABASE_RECV_STATE_BY_MSG,
                   SERVER_TIMER,
                   DATABASE_TIMER,
                   CLIENT_TYPE,
                   SIGNED_IN_STATE,
                   SENSOR_ACT_FLAG,
                   SENSOR_MOB_FLAG,
                   USER_TYPE,
                   CID_TYPE

};